name: eciftci
description: E-Çiftçi Uygulaması ile Çiftçilerin günlük hayatlarını kolaylaştırmak için geliştirilmiş bir mobil uygulamadır.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  # database
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6


  # core
  kartal: ^3.5.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  data_connection_checker_nulls: ^0.0.2
  cached_network_image: ^3.3.1
  intro_slider: ^3.0.10


  # utility
  loading_animation_widget: ^1.2.0+4
  hexcolor: ^3.0.1
  contained_tab_bar_view: ^0.8.0
  google_fonts: ^5.1.0
  carousel_slider: ^4.2.1
  logger: ^2.0.2
  url_launcher: ^6.1.6
  animate_do: ^3.1.2
  flutter_datetime_picker_plus: ^2.1.0
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # icons
    - assets/icons/app_icon/
    - assets/icons/register_icon/
    - assets/icons/password_icon/
  # images
    - assets/images/splashslider_img/
    - assets/images/logreg_img/
    - assets/images/connectionerror_img/
    - assets/images/incomegoes_img/
    - assets/images/plots_img/
  #   - images/a_dot_ham.jpeg





  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


